/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

/**
 *
 * @author Desk-strako
 */
public class Pincipal extends javax.swing.JFrame {

    /**
     * Creates new form Pincipal
     */
    public Pincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jButton8 = new javax.swing.JButton();
        player1 = new javax.swing.JTextField();
        player2 = new javax.swing.JTextField();
        player3 = new javax.swing.JTextField();
        player4 = new javax.swing.JTextField();
        player6 = new javax.swing.JTextField();
        player7 = new javax.swing.JTextField();
        player8 = new javax.swing.JTextField();
        player5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        icoWoker = new javax.swing.JLabel();
        icoFierro = new javax.swing.JLabel();
        icoLoki = new javax.swing.JLabel();
        icoXtensiv = new javax.swing.JLabel();
        icoEduardo = new javax.swing.JLabel();
        icoMustafunk = new javax.swing.JLabel();
        icoStrako = new javax.swing.JLabel();
        icoRetro = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 102, 102));
        jButton8.setText("0");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jDesktop.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        player1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player1.setForeground(new java.awt.Color(255, 255, 255));
        player1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player1.setText("Strako");
        player1.setBorder(null);
        player1.setOpaque(false);
        player1.setPreferredSize(new java.awt.Dimension(59, 20));
        jDesktop.add(player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 60, 60, -1));

        player2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player2.setForeground(new java.awt.Color(255, 255, 255));
        player2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player2.setText("Retroneon");
        player2.setBorder(null);
        player2.setOpaque(false);
        player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2ActionPerformed(evt);
            }
        });
        jDesktop.add(player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 60, -1, -1));

        player3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player3.setForeground(new java.awt.Color(255, 255, 255));
        player3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player3.setText("LokideKill");
        player3.setBorder(null);
        player3.setOpaque(false);
        player3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player3ActionPerformed(evt);
            }
        });
        jDesktop.add(player3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        player4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player4.setForeground(new java.awt.Color(255, 255, 255));
        player4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player4.setText("Xtensiv");
        player4.setBorder(null);
        player4.setOpaque(false);
        player4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player4ActionPerformed(evt);
            }
        });
        jDesktop.add(player4, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 310, -1, -1));

        player6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player6.setForeground(new java.awt.Color(255, 255, 255));
        player6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player6.setText("Mustafunk");
        player6.setBorder(null);
        player6.setOpaque(false);
        player6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player6ActionPerformed(evt);
            }
        });
        jDesktop.add(player6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        player7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player7.setForeground(new java.awt.Color(255, 255, 255));
        player7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player7.setText("FierroCompa");
        player7.setBorder(null);
        player7.setOpaque(false);
        player7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player7ActionPerformed(evt);
            }
        });
        jDesktop.add(player7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        player8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player8.setForeground(new java.awt.Color(255, 255, 255));
        player8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player8.setText("WOKER");
        player8.setBorder(null);
        player8.setOpaque(false);
        jDesktop.add(player8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        player5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player5.setForeground(new java.awt.Color(255, 255, 255));
        player5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player5.setText("Eduardo/442");
        player5.setBorder(null);
        player5.setOpaque(false);
        player5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player5ActionPerformed(evt);
            }
        });
        jDesktop.add(player5, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 190, 110, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("0");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktop.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("0");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktop.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("0");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDesktop.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("0");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDesktop.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("0");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jDesktop.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 102));
        jButton6.setText("0");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jDesktop.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setText("0");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jDesktop.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        icoWoker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icoWoker.png"))); // NOI18N
        jDesktop.add(icoWoker, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 380, -1, -1));

        icoFierro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icoFierro.png"))); // NOI18N
        jDesktop.add(icoFierro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        icoLoki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icoLokidekill.png"))); // NOI18N
        jDesktop.add(icoLoki, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        icoXtensiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icoXtensiv.png"))); // NOI18N
        jDesktop.add(icoXtensiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 255, -1, -1));

        icoEduardo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icoRetro1.png"))); // NOI18N
        jDesktop.add(icoEduardo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 140, -1, -1));

        icoMustafunk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icoMustafunk.png"))); // NOI18N
        jDesktop.add(icoMustafunk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        icoStrako.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icoStrako.png"))); // NOI18N
        jDesktop.add(icoStrako, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 10, -1, -1));

        icoRetro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icoRetro2.png"))); // NOI18N
        jDesktop.add(icoRetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 10, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backgrond1.png"))); // NOI18N
        jDesktop.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 490));

        getContentPane().add(jDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int [] score = {0,0,0,0,0,0,0,0,0};
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     score[1]++;
        String s1 = String.valueOf(score[1]);
        jButton1.setText(s1);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         score[2]++;
        String s2 = String.valueOf(score[2]);
        jButton2.setText(s2);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         score[3]++;
        String s3 = String.valueOf(score[3]);
        jButton3.setText(s3);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         score[4]++;
        String s4 = String.valueOf(score[4]);
        jButton4.setText(s4);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         score[5]++;
        String s5 = String.valueOf(score[5]);
        jButton5.setText(s5);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         score[6]++;
        String s6 = String.valueOf(score[6]);
        jButton6.setText(s6);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         score[7]++;
        String s7 = String.valueOf(score[7]);
        jButton7.setText(s7);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         score[8]++;
        String s8 = String.valueOf(score[8]);
        jButton8.setText(s8);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player2ActionPerformed

    private void player4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void player6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player6ActionPerformed

    private void player5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player5ActionPerformed

    private void player3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player3ActionPerformed

    private void player7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel icoEduardo;
    private javax.swing.JLabel icoFierro;
    private javax.swing.JLabel icoLoki;
    private javax.swing.JLabel icoMustafunk;
    private javax.swing.JLabel icoRetro;
    private javax.swing.JLabel icoStrako;
    private javax.swing.JLabel icoWoker;
    private javax.swing.JLabel icoXtensiv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField player1;
    private javax.swing.JTextField player2;
    private javax.swing.JTextField player3;
    private javax.swing.JTextField player4;
    private javax.swing.JTextField player5;
    private javax.swing.JTextField player6;
    private javax.swing.JTextField player7;
    private javax.swing.JTextField player8;
    // End of variables declaration//GEN-END:variables
}
